#!/usr/bin/env sh
#              _           _          
#             | |         (_)         
#  _   _  __ _| |__   __ _ _ _ __ ___ 
# | | | |/ _` | '_ \ / _` | | '__/ __|
# | |_| | (_| | |_) | (_| | | | | (__ 
#  \__, |\__,_|_.__/ \__,_|_|_|  \___|
#   __/ |                             
#  |___/                              

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   12

# Spaces
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five
yabai -m space 6 --label six
yabai -m space 7 --label seven
yabai -m space 8 --label eight
yabai -m space 9 --label nine

# Move some apps to specific spaces
yabai -m rule --add app="^Spotify$" space=8
yabai -m rule --add app="^Todoist$" space=8
yabai -m rule --add app="^Discord$" space=9
yabai -m rule --add app="^Messages$" space=9

# Float preferences
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Opening .*$" manage=off

yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app="^Finder$" manage=off

# Global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# Window border settings
yabai -m config window_border                on
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xfffe8019
yabai -m config normal_window_border_color   0xff282828
yabai -m config insert_feedback_color        0xffebdbb2 

echo "yabai configuration loaded..."
